steps:
  - label: "Unity Editor ${UnityVersion}-${Unity_Changeset} Linux Server"
    command: "docker build . --file ./editor/Dockerfile -t ${DockerUsername}/unity_editor:${UnityVersion}-linux-server --build-arg=version=${UnityVersion} --build-arg=changeSet=${UnityChangeset} --build-arg=module=linux-server"